from typing import Any, overload

class MultiUSRP:
    def __init__(self, token: str) -> None: ...
    @property
    def remoterf_capabilities(self) -> dict[str, Any]: ...
    def close(self) -> bool: ...
    def get_pp_string(self) -> Any: ...
    def get_mboard_name(self, mboard: Any = 0) -> Any: ...
    def get_num_mboards(self) -> Any: ...
    def get_tree(self) -> Any: ...
    def get_radio_control(self, chan: Any = 0) -> Any: ...
    def get_mb_controller(self, mboard: Any = 0) -> Any: ...
    def get_usrp_rx_info(self, chan: Any = 0) -> Any: ...
    def get_usrp_tx_info(self, chan: Any = 0) -> Any: ...
    def get_rx_num_channels(self) -> Any: ...
    def get_tx_num_channels(self) -> Any: ...
    def get_rx_radio_channel(self, chan: Any = 0) -> Any: ...
    def get_tx_radio_channel(self, chan: Any = 0) -> Any: ...
    def set_master_clock_rate(self, rate: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_master_clock_rate(self, mboard: Any = 0) -> Any: ...
    def get_master_clock_rate_range(self, mboard: Any = 18446744073709551615) -> Any: ...
    def get_time_now(self, mboard: Any = 0) -> Any: ...
    def get_time_last_pps(self, mboard: Any = 0) -> Any: ...
    def set_time_now(self, time_spec: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def set_time_next_pps(self, time_spec: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def set_time_unknown_pps(self, time_spec: Any) -> Any: ...
    def get_time_synchronized(self) -> Any: ...
    def set_command_time(self, time_spec: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def clear_command_time(self, mboard: Any = 18446744073709551615) -> Any: ...
    def issue_stream_cmd(self, rate: Any, chan: Any = 18446744073709551615) -> Any: ...
    def set_clock_source(self, source: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_clock_source(self, mboard: Any) -> Any: ...
    def get_clock_sources(self, mboard: Any) -> Any: ...
    def set_time_source(self, source: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_time_source(self, mboard: Any) -> Any: ...
    def get_time_sources(self, mboard: Any) -> Any: ...
    @overload
    def set_sync_source(self, clock_source: Any, time_source: Any, mboard: Any = 18446744073709551615) -> Any: ...
    @overload
    def set_sync_source(self, sync_source: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_sync_source(self, mboard: Any) -> Any: ...
    def get_sync_sources(self, mboard: Any) -> Any: ...
    def set_clock_source_out(self, enb: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def set_time_source_out(self, enb: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_mboard_sensor_names(self, mboard: Any = 0) -> Any: ...
    def get_mboard_sensor(self, name: Any, mboard: Any = 0) -> Any: ...
    def set_rx_subdev_spec(self, spec: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_rx_subdev_spec(self, mboard: Any = 0) -> Any: ...
    def get_rx_subdev_name(self, chan: Any = 0) -> Any: ...
    def set_rx_rate(self, rate: Any, chan: Any = 18446744073709551615) -> Any: ...
    def get_rx_rate(self, chan: Any = 0) -> Any: ...
    def get_rx_rates(self, chan: Any = 0) -> Any: ...
    def set_rx_spp(self, spp: Any, chan: Any = 18446744073709551615) -> Any: ...
    def set_rx_freq(self, tune_request: Any, chan: Any = 0) -> Any: ...
    def get_rx_freq(self, chan: Any = 0) -> Any: ...
    def get_rx_freq_range(self, chan: Any = 0) -> Any: ...
    def get_fe_rx_freq_range(self, chan: Any = 0) -> Any: ...
    def get_rx_lo_names(self, chan: Any = 0) -> Any: ...
    def set_rx_lo_source(self, src: Any, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_rx_lo_source(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_rx_lo_sources(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def set_rx_lo_export_enabled(self, enb: Any, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_rx_lo_export_enabled(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def set_rx_lo_freq(self, freq: Any, name: Any, chan: Any = 0) -> Any: ...
    def get_rx_lo_freq(self, name: Any, chan: Any = 0) -> Any: ...
    def get_rx_lo_freq_range(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_gain(self, gain: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_gain(self, gain: Any, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_rx_gain(self, chan: Any = 0) -> Any: ...
    @overload
    def get_rx_gain(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_rx_gain_range(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_rx_gain_range(self, chan: Any = 0) -> Any: ...
    def get_rx_gain_names(self, chan: Any = 0) -> Any: ...
    def set_normalized_rx_gain(self, gain: Any, chan: Any = 0) -> Any: ...
    def get_normalized_rx_gain(self, chan: Any = 0) -> Any: ...
    def set_rx_agc(self, enable: Any, chan: Any = 0) -> Any: ...
    def set_rx_gain_profile(self, profile: Any, chan: Any = 0) -> Any: ...
    def get_rx_gain_profile(self, chan: Any = 0) -> Any: ...
    def get_rx_gain_profile_names(self, chan: Any = 0) -> Any: ...
    def has_rx_power_reference(self, chan: Any = 0) -> Any: ...
    def set_rx_power_reference(self, power_dbm: Any, chan: Any = 0) -> Any: ...
    def get_rx_power_reference(self, chan: Any = 0) -> Any: ...
    def get_rx_power_range(self, chan: Any = 0) -> Any: ...
    def set_rx_antenna(self, ant: Any, chan: Any = 0) -> Any: ...
    def get_rx_antenna(self, chan: Any = 0) -> Any: ...
    def get_rx_antennas(self, chan: Any = 0) -> Any: ...
    def set_rx_bandwidth(self, bandwidth: Any, chan: Any = 0) -> Any: ...
    def get_rx_bandwidth(self, chan: Any = 0) -> Any: ...
    def get_rx_bandwidth_range(self, chan: Any = 0) -> Any: ...
    def get_rx_sensor_names(self, chan: Any = 0) -> Any: ...
    def get_rx_sensor(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_dc_offset(self, offset: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_dc_offset(self, enb: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_iq_balance(self, correction: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_rx_iq_balance(self, enb: Any, chan: Any = 0) -> Any: ...
    def get_rx_dboard_iface(self, chan: Any = 0) -> Any: ...
    def set_tx_subdev_spec(self, spec: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_tx_subdev_spec(self, mboard: Any = 0) -> Any: ...
    def get_tx_subdev_name(self, chan: Any = 0) -> Any: ...
    def set_tx_rate(self, rate: Any, chan: Any = 18446744073709551615) -> Any: ...
    def get_tx_rate(self, chan: Any = 0) -> Any: ...
    def get_tx_rates(self, chan: Any = 0) -> Any: ...
    def set_tx_freq(self, tune_request: Any, chan: Any = 0) -> Any: ...
    def get_tx_freq(self, chan: Any = 0) -> Any: ...
    def get_tx_freq_range(self, chan: Any = 0) -> Any: ...
    def get_fe_tx_freq_range(self, chan: Any = 0) -> Any: ...
    def get_tx_lo_names(self, chan: Any = 0) -> Any: ...
    def set_tx_lo_source(self, src: Any, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_tx_lo_source(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_tx_lo_sources(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def set_tx_lo_export_enabled(self, enb: Any, name: Any = 'all', chan: Any = 0) -> Any: ...
    def get_tx_lo_export_enabled(self, name: Any = 'all', chan: Any = 0) -> Any: ...
    def set_tx_lo_freq(self, freq: Any, name: Any, chan: Any = 0) -> Any: ...
    def get_tx_lo_freq(self, name: Any, chan: Any = 0) -> Any: ...
    def get_tx_lo_freq_range(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_tx_gain(self, gain: Any, chan: Any = 0) -> Any: ...
    @overload
    def set_tx_gain(self, gain: Any, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_tx_gain(self, chan: Any = 0) -> Any: ...
    @overload
    def get_tx_gain(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_tx_gain_range(self, name: Any, chan: Any = 0) -> Any: ...
    @overload
    def get_tx_gain_range(self, chan: Any = 0) -> Any: ...
    def get_tx_gain_names(self, chan: Any = 0) -> Any: ...
    def set_normalized_tx_gain(self, gain: Any, chan: Any = 0) -> Any: ...
    def get_normalized_tx_gain(self, chan: Any = 0) -> Any: ...
    def set_tx_gain_profile(self, profile: Any, chan: Any = 0) -> Any: ...
    def get_tx_gain_profile(self, chan: Any = 0) -> Any: ...
    def get_tx_gain_profile_names(self, chan: Any = 0) -> Any: ...
    def has_tx_power_reference(self, chan: Any = 0) -> Any: ...
    def set_tx_power_reference(self, power_dbm: Any, chan: Any = 0) -> Any: ...
    def get_tx_power_reference(self, chan: Any = 0) -> Any: ...
    def get_tx_power_range(self, chan: Any = 0) -> Any: ...
    def set_tx_antenna(self, ant: Any, chan: Any = 0) -> Any: ...
    def get_tx_antenna(self, chan: Any = 0) -> Any: ...
    def get_tx_antennas(self, chan: Any = 0) -> Any: ...
    def set_tx_bandwidth(self, bandwidth: Any, chan: Any = 0) -> Any: ...
    def get_tx_bandwidth(self, chan: Any = 0) -> Any: ...
    def get_tx_bandwidth_range(self, chan: Any = 0) -> Any: ...
    def get_tx_sensor_names(self, chan: Any = 0) -> Any: ...
    def get_tx_sensor(self, name: Any, chan: Any = 0) -> Any: ...
    def set_tx_dc_offset(self, offset: Any, chan: Any = 0) -> Any: ...
    def set_tx_iq_balance(self, correction: Any, chan: Any = 0) -> Any: ...
    def get_tx_dboard_iface(self, chan: Any = 0) -> Any: ...
    def get_rx_stream(self, stream_args: Any) -> Any: ...
    def get_tx_stream(self, stream_args: Any) -> Any: ...
    def get_gpio_banks(self, mboard: Any) -> Any: ...
    def set_gpio_attr(self, bank: Any, attr: Any, value: Any, mask: Any = 4294967295, mboard: Any = 0) -> Any: ...
    def get_gpio_attr(self, bank: Any, attr: Any, mboard: Any = 0) -> Any: ...
    def get_gpio_srcs(self, bank: Any, mboard: Any = 0) -> Any: ...
    def get_gpio_src(self, bank: Any, mboard: Any = 0) -> Any: ...
    def set_gpio_src(self, bank: Any, src: Any, mboard: Any = 0) -> Any: ...
    def get_gpio_src_banks(self, mboard: Any = 0) -> Any: ...
    def get_rx_filter_names(self, chan: Any) -> Any: ...
    def get_rx_filter(self, name: Any, chan: Any) -> Any: ...
    def set_rx_filter(self, name: Any, filter: Any, chan: Any) -> Any: ...
    def get_tx_filter_names(self, chan: Any) -> Any: ...
    def get_tx_filter(self, name: Any, chan: Any) -> Any: ...
    def set_tx_filter(self, name: Any, filter: Any, chan: Any) -> Any: ...
    def set_user_register(self, addr: Any, data: Any, mboard: Any = 18446744073709551615) -> Any: ...
    def get_user_settings_iface(self, chan: Any = 0) -> Any: ...
    def recv_num_samps(self, num_samps: Any, freq: Any, rate: Any = 1000000.0, channels: Any = [0], gain: Any = 10, start_time: Any = None, streamer: Any = None) -> Any: ...
    def send_waveform(self, waveform_proto: Any, duration: Any, freq: Any, rate: Any = 1000000.0, channels: Any = [0], gain: Any = 10, start_time: Any = None, streamer: Any = None) -> Any: ...

uhd: Any
