# Copyright (C) 2026 RemoteRF
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: global_auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'global_auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import grpc_pb2 as grpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11global_auth.proto\x12\tremote_rf\x1a\ngrpc.proto\"b\n\x18\x45xchangeAssertionRequest\x12\x11\n\tassertion\x18\x01 \x01(\t\x12\x19\n\x11\x63lient_request_id\x18\x02 \x01(\t\x12\x18\n\x10protocol_version\x18\x03 \x01(\t\"\x87\x02\n\x19\x45xchangeAssertionResponse\x12\x16\n\x0elocal_username\x18\x01 \x01(\t\x12\x1b\n\x13local_session_token\x18\x02 \x01(\t\x12\x18\n\x10local_account_id\x18\x03 \x01(\x03\x12\x1a\n\x12session_expires_at\x18\x04 \x01(\t\x12\x15\n\rdeployment_id\x18\x05 \x01(\t\x12%\n\x1d\x65\x66\x66\x65\x63tive_policy_summary_json\x18\x06 \x01(\t\x12\x18\n\x10protocol_version\x18\x07 \x01(\t\x12\'\n\x05\x65rror\x18\x08 \x01(\x0b\x32\x18.remote_rf.ErrorEnvelope2n\n\x0cGlobalAuthV1\x12^\n\x11\x45xchangeAssertion\x12#.remote_rf.ExchangeAssertionRequest\x1a$.remote_rf.ExchangeAssertionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'global_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGEASSERTIONREQUEST']._serialized_start=44
  _globals['_EXCHANGEASSERTIONREQUEST']._serialized_end=142
  _globals['_EXCHANGEASSERTIONRESPONSE']._serialized_start=145
  _globals['_EXCHANGEASSERTIONRESPONSE']._serialized_end=408
  _globals['_GLOBALAUTHV1']._serialized_start=410
  _globals['_GLOBALAUTHV1']._serialized_end=520
# @@protoc_insertion_point(module_scope)
