# Copyright (C) 2026 RemoteRF
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import global_auth_pb2 as global__auth__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in global_auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlobalAuthV1Stub:
    """RemoteRF Global v1.0 — additive, optional, and deliberately kept in its
    own .proto file rather than appended to grpc.proto: grpc.proto is shared
    byte-for-byte with the RemoteRF client's own copy (both register a
    descriptor under the identical name "grpc.proto" in protobuf's process-
    global default pool, so any content drift between the two would collide
    whenever both are imported in one process — e.g. this repo's own
    server+client integration tests). global_auth.proto instead registers
    under its own distinct name and only imports grpc.proto for the existing
    ErrorEnvelope type, so grpc.proto itself never needs to change for this
    feature.

    Registered on the same TLS gRPC server/port as every other service here;
    when Global is disabled on this deployment, ExchangeAssertion always
    returns a populated `error` (code "global_disabled") rather than the
    server refusing to start.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeAssertion = channel.unary_unary(
                '/remote_rf.GlobalAuthV1/ExchangeAssertion',
                request_serializer=global__auth__pb2.ExchangeAssertionRequest.SerializeToString,
                response_deserializer=global__auth__pb2.ExchangeAssertionResponse.FromString,
                _registered_method=True)


class GlobalAuthV1Servicer:
    """RemoteRF Global v1.0 — additive, optional, and deliberately kept in its
    own .proto file rather than appended to grpc.proto: grpc.proto is shared
    byte-for-byte with the RemoteRF client's own copy (both register a
    descriptor under the identical name "grpc.proto" in protobuf's process-
    global default pool, so any content drift between the two would collide
    whenever both are imported in one process — e.g. this repo's own
    server+client integration tests). global_auth.proto instead registers
    under its own distinct name and only imports grpc.proto for the existing
    ErrorEnvelope type, so grpc.proto itself never needs to change for this
    feature.

    Registered on the same TLS gRPC server/port as every other service here;
    when Global is disabled on this deployment, ExchangeAssertion always
    returns a populated `error` (code "global_disabled") rather than the
    server refusing to start.
    """

    def ExchangeAssertion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlobalAuthV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeAssertion': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeAssertion,
                    request_deserializer=global__auth__pb2.ExchangeAssertionRequest.FromString,
                    response_serializer=global__auth__pb2.ExchangeAssertionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_rf.GlobalAuthV1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remote_rf.GlobalAuthV1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlobalAuthV1:
    """RemoteRF Global v1.0 — additive, optional, and deliberately kept in its
    own .proto file rather than appended to grpc.proto: grpc.proto is shared
    byte-for-byte with the RemoteRF client's own copy (both register a
    descriptor under the identical name "grpc.proto" in protobuf's process-
    global default pool, so any content drift between the two would collide
    whenever both are imported in one process — e.g. this repo's own
    server+client integration tests). global_auth.proto instead registers
    under its own distinct name and only imports grpc.proto for the existing
    ErrorEnvelope type, so grpc.proto itself never needs to change for this
    feature.

    Registered on the same TLS gRPC server/port as every other service here;
    when Global is disabled on this deployment, ExchangeAssertion always
    returns a populated `error` (code "global_disabled") rather than the
    server refusing to start.
    """

    @staticmethod
    def ExchangeAssertion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote_rf.GlobalAuthV1/ExchangeAssertion',
            global__auth__pb2.ExchangeAssertionRequest.SerializeToString,
            global__auth__pb2.ExchangeAssertionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
